
name: main
on: ["push"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - uses: action/setup-node@v4
        with:
         node-version: 18
      - run: node ./script/hello.js


