# Workflow name
name: deploy to render
# event >> trigger
on: ["push", "pull_request"]

jobs:
  # name
  build-and-deploy:
	  # OS or Platform
    runs-on: ubuntu-latest

    # steps
    steps:
      - uses: action/check@v3
      - uses: action/setup-node@v4
        with: 
         node-version: 18

			#run the Script file				 
      - name: deploy render
        run: npm install


