# Workflow name
name: deploy to render
# event >> trigger
on: ["push", "pull_request"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: action/check@v3
      - uses: action/setup-node@v4
        with: 
         node-version: 18
      - name: deploy render
        run: node ./script/hello.js


